name: Docker container build workflow

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the PROCESS Docker image
        run: |
          docker build . -t ghcr.io/timothy-nunn/process-ci:latest
          docker push ghcr.io/timothy-nunn/process-ci:latest
