name: Docker container build workflow

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      build_container: ${{ steps.changes.outputs.effects_container }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for changed files effecting the container
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            build_container:
              - 'Dockerfile'
              - 'requirements.txt'

  docker:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ github.ref == 'refs/heads/master' &&  needs.changes.outputs.build_container }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the PROCESS Docker image
        run: |
          docker build . -t ghcr.io/timothy-nunn/process-ci:latest
          docker push ghcr.io/timothy-nunn/process-ci:latest

  test-job:
    runs-on: ubuntu-latest
    needs: docker
    container:
      image: ghcr.io/timothy-nunn/process-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: pip freeze
